import { Link } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { Plus, UploadCloud, QrCode, RefreshCw, Mail, Ban, FileText, CheckCircle2 } from "lucide-react";
import Layout from "../components/Layout";
import { demoCertificates } from "../data";
import { loadIssuedCertificates } from "../certificateStore";

function val(data,key){const e=data?.[key];if(e!==undefined&&e!==null)return String(e);const f=Object.entries(data||{}).find(([k])=>String(k).toLowerCase()===String(key).toLowerCase());return f?String(f[1]??""):""}
function nameOf(r){return val(r?.data,"name")||val(r?.data,"student_name")||val(r?.data,"recipient_name")||"Participant"}
function courseOf(r){return val(r?.data,"course")||r?.templateName||"Certificate"}
function dateOf(r){const d=new Date(r?.issuedAt||"");return Number.isNaN(d.getTime())?"—":d.toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"})}
export default function Dashboard(){const [records,setRecords]=useState([]);const [updated,setUpdated]=useState(new Date());const refresh=()=>{setRecords(loadIssuedCertificates());setUpdated(new Date())};useEffect(()=>{refresh();const f=()=>refresh();window.addEventListener("certichain:issued-certificates-updated",f);const i=setInterval(refresh,1500);return()=>{window.removeEventListener("certichain:issued-certificates-updated",f);clearInterval(i)}},[]);
 const metrics=useMemo(()=>{const now=new Date(),day=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime(),month=new Date(now.getFullYear(),now.getMonth(),1).getTime(),year=new Date(now.getFullYear(),0,1).getTime();return {total:records.length,today:records.filter(r=>new Date(r.issuedAt).getTime()>=day).length,month:records.filter(r=>new Date(r.issuedAt).getTime()>=month).length,year:records.filter(r=>new Date(r.issuedAt).getTime()>=year).length,sent:records.filter(r=>r.emailStatus==="Sent").length,failed:records.filter(r=>r.emailStatus==="Failed").length,pending:records.filter(r=>!r.emailStatus||["Not sent","Sending…"].includes(r.emailStatus)).length,disq:records.filter(r=>r.status==="Disqualified").length,templates:new Set(records.map(r=>r.templateId)).size}},[records]);
 const recent=useMemo(()=>records.slice().sort((a,b)=>new Date(b.issuedAt)-new Date(a.issuedAt)).slice(0,8),[records]); const courseCounts=useMemo(()=>{const m={};records.forEach(r=>{const k=courseOf(r);m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,5)},[records]);const max=Math.max(1,...courseCounts.map(x=>x[1]));
 return <Layout title="Dashboard" subtitle="Live certificate operations"><div className="mx-auto max-w-7xl space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Total Certificates",metrics.total,FileText], ["Today",metrics.today,CheckCircle2],["Emails Sent",metrics.sent,Mail],["Emails Failed",metrics.failed,Ban],["Disqualified",metrics.disq,Ban]].map(([label,value,Icon])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon size={19} className="text-blue-600"/><div className="mt-4 text-xs font-medium uppercase tracking-wider text-slate-400">{label}</div><div className="mt-1 text-3xl font-bold">{value}</div></div>)}</div>
 <div className="grid gap-4 md:grid-cols-4"><div className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs text-slate-400">This month</span><b className="mt-1 block text-2xl">{metrics.month}</b></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs text-slate-400">This year</span><b className="mt-1 block text-2xl">{metrics.year}</b></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs text-slate-400">Pending emails</span><b className="mt-1 block text-2xl">{metrics.pending}</b></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs text-slate-400">Templates used</span><b className="mt-1 block text-2xl">{metrics.templates}</b></div></div>
 <div className="flex flex-wrap gap-2"><Link to="/templates/new" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white"><Plus size={16}/> Create Template</Link><Link to="/issue-certificate" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><UploadCloud size={16}/> Issue Certificate</Link><Link to="/verify" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold"><QrCode size={16}/> Verify</Link></div>
 <div className="grid gap-5 lg:grid-cols-[1.45fr_.9fr]"><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><div className="flex items-center gap-2"><h2 className="font-bold">Recent certificates</h2><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-emerald-700">Live</span></div><p className="mt-1 text-sm text-slate-500">Updates automatically when a certificate is issued, emailed or disqualified.</p><div className="mt-1 flex items-center gap-1 text-[11px] text-slate-400"><RefreshCw size={11}/> Updated {updated.toLocaleTimeString()}</div></div><Link to="/certificates" className="text-sm font-semibold text-blue-600">View all</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[700px]"><thead><tr className="border-b border-slate-100 text-left text-xs uppercase tracking-wider text-slate-400"><th className="px-5 py-4">Certificate</th><th className="px-5 py-4">Participant</th><th className="px-5 py-4">Course</th><th className="px-5 py-4">Status</th></tr></thead><tbody>{recent.length?recent.map(r=><tr key={r.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><Link to={`/certificates/${r.id}`} className="font-semibold text-blue-600">{r.id}</Link><div className="text-xs text-slate-400">{dateOf(r)}</div></td><td className="px-5 py-4 text-sm">{nameOf(r)}<div className="text-xs text-slate-400">{r.email||val(r.data,"email")||"No email"}</div></td><td className="px-5 py-4 text-sm text-slate-600">{courseOf(r)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${r.status==="Disqualified"?"bg-rose-50 text-rose-700":r.emailStatus==="Sent"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{r.status==="Disqualified"?"Disqualified":r.emailStatus==="Sent"?"Emailed":"Issued"}</span></td></tr>):<tr><td colSpan="4" className="px-5 py-12 text-center text-sm text-slate-500">No certificates have been issued yet.</td></tr>}</tbody></table></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Certificates by course</h2><p className="mt-1 text-xs text-slate-400">Top five courses in the live registry</p><div className="mt-6 space-y-4">{courseCounts.length?courseCounts.map(([course,count])=><div key={course}><div className="flex justify-between text-sm"><span className="truncate pr-3">{course}</span><b>{count}</b></div><div className="mt-2 h-2.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${count/max*100}%`}}/></div></div>):<div className="py-10 text-center text-sm text-slate-500">No course data yet.</div>}</div></section></div></div></Layout>
}
