import Layout from "../components/Layout";
import TemplateCertificatePreview from "../components/TemplateCertificatePreview";
import { Link, useNavigate } from "react-router-dom";
import { useEffect, useMemo, useRef, useState } from "react";
import JSZip from "jszip";
import { ArrowLeft, Archive, CheckCircle2, Eye, FileText, Loader2, Mail, RefreshCcw, Send, ShieldCheck, Square, CheckSquare } from "lucide-react";
import { captureCertificatePng, certificatePngToPdf, downloadBlob } from "../certificateExport";
import { appendCertificateHistory, findIssuedCertificate, loadIssuedCertificates, updateIssuedCertificate } from "../certificateStore";
import { addAuditLog } from "../auditStore";
import { clearPendingEmailBatch, loadPendingEmailBatch } from "../emailBatchStore";
import { loadInstitutionSettings, renderEmailTemplate } from "../institutionStore";
import { getVerificationUrl } from "../verificationUrl";

const API = (import.meta.env.VITE_API_URL || "https://certichain-1-xc8l.onrender.com").replace(/\/$/, "");
function v(data,key){const exact=data?.[key];if(exact!==undefined&&exact!==null)return String(exact);const f=Object.entries(data||{}).find(([k])=>String(k).toLowerCase()===String(key).toLowerCase());return f?String(f[1]??""):""}
function nameOf(r){return v(r?.data,"name")||v(r?.data,"student_name")||v(r?.data,"recipient_name")||"Participant"}
function courseOf(r){return v(r?.data,"course")||r?.templateName||"Certificate"}
function validEmail(e){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(e||"").trim())}
function placeholder(e){const d=String(e||"").trim().toLowerCase().split("@").pop()||"";return ["example.com","example.org","example.net","invalid","localhost","test"].includes(d)||d.endsWith(".example")||d.endsWith(".test")||d.endsWith(".invalid")}
function escape(vv){return String(vv??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}
function b64FromArrayBuffer(buffer){let binary="";const bytes=new Uint8Array(buffer);const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+chunk,bytes.length)));return btoa(binary)}
async function statusApi(){const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),8000);try{const r=await fetch(`${API}/api/email/status`,{signal:controller.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Email backend returned HTTP ${r.status}`);return d;}catch(e){if(e?.name==="AbortError")throw new Error(`Email backend timed out: ${API}`);if(e instanceof TypeError)throw new Error(`Cannot reach email backend at ${API}`);throw e;}finally{window.clearTimeout(timer)}}

export default function EmailParticipants(){
 const navigate=useNavigate(); const refs=useRef({}); const [records,setRecords]=useState([]); const [batch,setBatch]=useState(null); const [selected,setSelected]=useState([]); const [busy,setBusy]=useState(false); const [zipBusy,setZipBusy]=useState(false); const [message,setMessage]=useState(""); const [serverReady,setServerReady]=useState(null); const [settings,setSettings]=useState(loadInstitutionSettings()); const [subject,setSubject]=useState(settings.emailTemplate.subject); const [body,setBody]=useState(settings.emailTemplate.body); const [previewId,setPreviewId]=useState(null);
 const refresh=()=>{const b=loadPendingEmailBatch();setBatch(b);const all=loadIssuedCertificates();const map=new Map(all.map(x=>[x.id,x]));const loaded=(b?.certificateIds||[]).map(id=>map.get(id)||findIssuedCertificate(id)).filter(Boolean);setRecords(loaded);setSelected(loaded.filter(r=>r.emailStatus!=="Sent").map(r=>r.id));};
 useEffect(()=>{refresh(); const f=()=>refresh(); window.addEventListener("certichain:issued-certificates-updated",f);return()=>window.removeEventListener("certichain:issued-certificates-updated",f)},[]);
 useEffect(()=>{statusApi().then(d=>setServerReady(d.configured?d:(d))).catch(()=>setServerReady(false))},[]);
 const summary=useMemo(()=>({total:records.length,sent:records.filter(r=>r.emailStatus==="Sent").length,failed:records.filter(r=>r.emailStatus==="Failed").length,pending:records.filter(r=>r.emailStatus!=="Sent"&&r.emailStatus!=="Failed").length}),[records]);
 const valuesFor=(r)=>({...(r.data||{}),name:nameOf(r),course:courseOf(r),certificate_id:r.id,verification_url:getVerificationUrl(r.id),institution_name:settings.institutionName});
 const buildMessage=async r=>{const c=refs.current[r.id];if(!c)throw new Error(`Certificate preview is not ready for ${r.id}.`);const png=await captureCertificatePng(c);const pdf=await certificatePngToPdf(png,r.template?.page?.orientation||"landscape");return {to:r.email,subject:renderEmailTemplate(subject,valuesFor(r)),html:`<div style="font-family:Arial,sans-serif;line-height:1.65;color:#0f172a">${renderEmailTemplate(body,valuesFor(r)).replace(/\n/g,"<br/>")}</div>`,certificateId:r.id,filename:`${r.id}.png`,contentType:"image/png",contentBase64:png.split(",")[1],attachments:[{filename:`${r.id}.pdf`,contentType:"application/pdf",contentBase64:b64FromArrayBuffer(await pdf.arrayBuffer())}]};};
 const send=async(ids=selected)=>{if(!serverReady?.connected){setMessage(serverReady?.message||"Gmail is not connected. Open Settings and connect Gmail before sending.");return} const targets=records.filter(r=>ids.includes(r.id));if(!targets.length){setMessage("Select at least one participant.");return}const invalid=targets.filter(r=>!validEmail(r.email)||placeholder(r.email));invalid.forEach(r=>updateIssuedCertificate(r.id,{emailStatus:"Failed",emailError:!validEmail(r.email)?"Invalid or missing email address.":"Placeholder email address. Replace example/test/localhost addresses."}));const eligible=targets.filter(r=>validEmail(r.email)&&!placeholder(r.email));if(!eligible.length){setMessage("No eligible participant emails were selected.");refresh();return}setBusy(true);setMessage(`Preparing ${eligible.length} certificate emails…`);try{const prepared=await Promise.allSettled(eligible.map(buildMessage));const ready=prepared.filter(x=>x.status==="fulfilled").map(x=>x.value);prepared.forEach((x,i)=>{if(x.status!=="fulfilled")updateIssuedCertificate(eligible[i].id,{emailStatus:"Failed",emailError:x.reason?.message||"Certificate rendering failed."})});if(!ready.length)throw new Error("No certificates could be prepared for email.");ready.forEach(r=>updateIssuedCertificate(r.certificateId,{emailStatus:"Sending…",emailError:null}));let response;try{response=await fetch(`${API}/api/email/certificates/bulk`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:ready})});}catch(e){throw new Error(e instanceof TypeError?`Cannot reach email backend at ${API}`:(e?.message||"Email backend request failed."));}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Bulk email request failed (HTTP ${response.status}).`);const map=new Map((data.results||[]).map(x=>[x.certificateId,x]));ready.forEach(m=>{const out=map.get(m.certificateId);updateIssuedCertificate(m.certificateId,out?.sent?{emailStatus:"Sent",emailSentAt:new Date().toISOString(),emailError:null}:{emailStatus:"Failed",emailError:out?.error||"Email sending failed.",emailErrorCode:out?.errorCode||null,emailResponseCode:out?.responseCode||null});appendCertificateHistory(m.certificateId,out?.sent?"Email sent":"Email failed",{to:m.to,error:out?.sent?null:out?.error||null});});const sent=data.sentCount||0,failed=(data.failedCount||0)+invalid.length+(prepared.length-ready.length);addAuditLog("Participant certificate email batch processed",{sent,failed,total:targets.length});setMessage(`${sent} email${sent===1?"":"s"} sent successfully${failed?` and ${failed} failed.`:"."}`);refresh();}catch(e){targets.forEach(r=>{if(r.emailStatus!=="Sent")updateIssuedCertificate(r.id,{emailStatus:"Failed",emailError:e.message||"Email service failed."})});setMessage(e.message||"Email delivery failed. Check the Render logs for the Gmail API error.");}finally{setBusy(false)}};
 const downloadZip=async()=>{setZipBusy(true);try{const zip=new JSZip();const folder=zip.folder("certichain-certificates");const manifest=[["certificate_id","recipient_name","email","course","status","issued_at"]];for(const r of records){const c=refs.current[r.id];const png=await captureCertificatePng(c);folder.file(`${r.id}.png`,png.split(",")[1],{base64:true});const pdf=await certificatePngToPdf(png,r.template?.page?.orientation||"landscape");folder.file(`${r.id}.pdf`,await pdf.arrayBuffer());manifest.push([r.id,nameOf(r),r.email,courseOf(r),r.emailStatus||"Not sent",r.issuedAt])}folder.file("manifest.csv",manifest.map(row=>row.map(x=>`"${String(x??"").replace(/"/g,'""')}"`).join(",")).join("\n"));const blob=await zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}});downloadBlob(blob,`CertiChain-Certificates-${new Date().toISOString().slice(0,10)}.zip`);addAuditLog("Certificate archive downloaded",{count:records.length});setMessage("Full ZIP downloaded with PNG and PDF for every issued certificate.");}catch(e){setMessage(e.message||"Unable to build ZIP.")}finally{setZipBusy(false)}};
 const toggle=(id)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]); const allSelected=records.length>0&&selected.length===records.length; const toggleAll=()=>setSelected(allSelected?[]:records.map(r=>r.id));
 if(!batch||!records.length)return <Layout title="Email Participants" subtitle="Participant certificate delivery"><div className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-10 text-center shadow-sm"><Mail className="mx-auto text-slate-400" size={40}/><h2 className="mt-4 text-xl font-bold">No pending participant batch</h2><p className="mt-2 text-sm text-slate-500">Issue a bulk certificate batch first.</p><Link to="/issue-certificate" className="mt-5 inline-flex rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Back to Issue Certificate</Link></div></Layout>;
 return <Layout title="Email Participants" subtitle="Send each issued certificate to its CSV recipient"><div className="mx-auto max-w-7xl space-y-5">
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="text-xs font-semibold uppercase tracking-wider text-blue-600">Step 3 • Email participants</div><h2 className="mt-1 text-2xl font-bold">Deliver the prepared certificates</h2><p className="mt-1 text-sm text-slate-500">{records.length} immutable certificates are ready. Each participant receives only their own certificate.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>navigate("/certificates")} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Issued Certificates</button><button onClick={()=>{clearPendingEmailBatch();navigate("/issue-certificate")}} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold"><ArrowLeft size={16}/> Back</button></div></div>
   <div className="mt-5 grid gap-3 sm:grid-cols-4"><div className="rounded-xl bg-slate-50 p-4"><div className="text-xs text-slate-500">Total</div><b className="text-2xl">{summary.total}</b></div><div className="rounded-xl bg-emerald-50 p-4"><div className="text-xs text-emerald-700">Sent</div><b className="text-2xl text-emerald-800">{summary.sent}</b></div><div className="rounded-xl bg-rose-50 p-4"><div className="text-xs text-rose-700">Failed</div><b className="text-2xl text-rose-800">{summary.failed}</b></div><div className="rounded-xl bg-blue-50 p-4"><div className="text-xs text-blue-700">Pending</div><b className="text-2xl text-blue-800">{summary.pending}</b></div></div>
   <div className={`mt-4 rounded-xl border px-4 py-3 text-sm ${serverReady?.connected?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>{serverReady?.connected?`Gmail API connected as ${serverReady.from}. Certificates will be sent from that Gmail account.`:serverReady?.message||"Email backend is not reachable/configured. Open Settings to connect Gmail."}{serverReady?.authUrl&&!serverReady?.connected?<button onClick={()=>window.location.href=serverReady.authUrl} className="ml-3 underline font-semibold">Connect Gmail</button>:null}</div>
   <div className="mt-5 grid gap-4 lg:grid-cols-[1fr_390px]"><section className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><h3 className="font-bold">Email template</h3><p className="mt-1 text-xs text-slate-500">Use certificate variables such as {'{{name}}'}, {'{{course}}'}, {'{{certificate_id}}'}, {'{{verification_url}}'} and {'{{institution_name}}'}.</p><label className="mt-4 block text-sm font-semibold">Subject<input value={subject} onChange={e=>setSubject(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 font-normal"/></label><label className="mt-3 block text-sm font-semibold">Body<textarea value={body} onChange={e=>setBody(e.target.value)} rows={7} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 font-normal"/></label></section><section className="rounded-2xl border border-slate-200 bg-white p-4"><div className="text-sm font-bold">Delivery actions</div><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>send(records.map(r=>r.id))} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy?<Loader2 className="animate-spin" size={17}/>:<Send size={17}/>}Send all</button><button disabled={busy||!selected.length} onClick={()=>send(selected)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold"><Send size={16}/>Send selected</button>{summary.failed>0&&<button disabled={busy} onClick={()=>send(records.filter(r=>r.emailStatus==="Failed").map(r=>r.id))} className="inline-flex items-center gap-2 rounded-xl border border-rose-200 bg-white px-4 py-3 text-sm font-semibold text-rose-700"><RefreshCcw size={16}/>Retry failed</button>}<button disabled={zipBusy||busy} onClick={downloadZip} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">{zipBusy?<Loader2 className="animate-spin" size={17}/>:<Archive size={17}/>}ZIP PNG + PDF</button></div>{message&&<div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-600">{message}</div>}<div className="mt-4 rounded-xl border border-slate-100 bg-white p-3 text-xs text-slate-500">Selected: <b className="text-slate-800">{selected.length}</b> · Sent: <b className="text-emerald-700">{summary.sent}</b> · Failed: <b className="text-rose-700">{summary.failed}</b></div></section></div>
  </div>
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-4"><button onClick={toggleAll} className="text-slate-500" title="Select all">{allSelected?<CheckSquare/>:<Square/>}</button><div><h3 className="font-bold">Participant queue</h3><p className="text-xs text-slate-500">Send selected participants or the entire batch. Delivery status is recorded without modifying certificate content.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px]"><thead><tr className="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-400"><th className="px-4 py-3"></th><th className="px-4 py-3">Participant</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Certificate</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{records.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="px-4 py-4"><button onClick={()=>toggle(r.id)} className="text-slate-500">{selected.includes(r.id)?<CheckSquare/>:<Square/>}</button></td><td className="px-4 py-4 text-sm font-medium">{nameOf(r)}<div className="text-xs text-slate-400">{courseOf(r)}</div></td><td className="px-4 py-4 text-sm text-slate-600">{r.email||"—"}</td><td className="px-4 py-4"><Link className="font-semibold text-blue-600" to={`/certificates/${r.id}`}>{r.id}</Link></td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${r.emailStatus==="Sent"?"bg-emerald-50 text-emerald-700":r.emailStatus==="Failed"?"bg-rose-50 text-rose-700":"bg-slate-100 text-slate-600"}`}>{r.emailStatus||"Not sent"}</span>{r.emailError&&<div className="mt-1 max-w-sm text-[11px] leading-4 text-rose-600">{r.emailError}</div>}</td><td className="px-4 py-4"><div className="flex gap-2"><button onClick={()=>setPreviewId(r.id)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-2 text-xs font-semibold"><Eye size={14}/> Preview</button><button disabled={busy} onClick={()=>send([r.id])} className="inline-flex items-center gap-1 rounded-lg bg-blue-600 px-2.5 py-2 text-xs font-semibold text-white disabled:opacity-50"><Send size={14}/> Send</button></div></td></tr>)}</tbody></table></div></section>
  <div className="pointer-events-none fixed left-[-25000px] top-0 opacity-0" aria-hidden="true">{records.map(r=><div key={r.id} ref={node=>{if(node)refs.current[r.id]=node;}} style={{width:1123}}><TemplateCertificatePreview template={r.template} form={r.data||{}} certificateId={r.id} exportMode/></div>)}</div>
  {previewId&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/70 p-4"><div className="max-h-[95vh] w-full max-w-6xl overflow-auto rounded-2xl bg-white p-4"><div className="mb-3 flex items-center justify-between"><div><b>Certificate preview</b><div className="text-xs text-slate-400">{previewId}</div></div><button onClick={()=>setPreviewId(null)} className="rounded-lg border px-3 py-2 text-sm">Close</button></div><TemplateCertificatePreview template={records.find(r=>r.id===previewId)?.template} form={records.find(r=>r.id===previewId)?.data||{}} certificateId={previewId}/></div></div>}
 </div></Layout>
}
