import Layout from "../components/Layout";
import { useEffect, useState } from "react";
import { Save, Wallet, Database, Building2, Hash, Mail, Download, Upload, ShieldCheck, RefreshCw } from "lucide-react";
import { loadInstitutionSettings, saveInstitutionSettings } from "../institutionStore";
import { loadAuditLogs } from "../auditStore";
import { getSessionUser, saveUser } from "../authStore";
import { loadIssuedCertificates } from "../certificateStore";

export default function Settings(){
 const API=(import.meta.env.VITE_API_URL||"https://certichain-1-xc8l.onrender.com").replace(/\/$/,"");
 const [gmail,setGmail]=useState({loading:true});
 const [settings,setSettings]=useState(loadInstitutionSettings()); const [saved,setSaved]=useState(false); const [profile,setProfile]=useState(getSessionUser()||{name:"CertiChain Admin",email:"admin@certichain.local",role:"Admin"});
 const change=(section,key,value)=>setSettings(s=>section?{...s,[section]:{...s[section],[key]:value}}:{...s,[key]:value});
 const save=()=>{saveInstitutionSettings(settings);setSaved(true);setTimeout(()=>setSaved(false),2200)};
 const image=(key,file)=>{const reader=new FileReader();reader.onload=()=>change(null,key,reader.result);reader.readAsDataURL(file)};
 const backup=()=>{const payload={exportedAt:new Date().toISOString(),settings,templates:JSON.parse(localStorage.getItem("certichain-templates")||"[]"),certificates:loadIssuedCertificates(),auditLogs:loadAuditLogs()};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));a.download=`certichain-backup-${new Date().toISOString().slice(0,10)}.json`;a.click()};
 const restore=(file)=>{const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(data.settings)localStorage.setItem("certichain-institution-settings",JSON.stringify(data.settings));if(data.templates)localStorage.setItem("certichain-templates",JSON.stringify(data.templates));if(data.certificates)localStorage.setItem("certichain-issued-certificates",JSON.stringify(data.certificates));if(data.auditLogs)localStorage.setItem("certichain-audit-logs",JSON.stringify(data.auditLogs));setSettings(loadInstitutionSettings());setSaved(true);setTimeout(()=>window.location.reload(),900)}catch{alert("Backup file is invalid.")}};reader.readAsText(file)};
 const connectGmail=()=>{window.location.href=gmail.authUrl||`${API}/api/email/google/auth`};
 useEffect(()=>{let active=true;fetch(`${API}/api/email/status`).then(r=>r.json()).then(d=>{if(active)setGmail({loading:false,...d})}).catch(()=>{if(active)setGmail({loading:false,configured:false,connected:false,message:"Cannot reach Gmail backend."})});return()=>{active=false}},[API]);
 return <Layout title="Settings" subtitle="Institution configuration and platform administration"><div className="mx-auto max-w-7xl space-y-5">
   <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><div className="text-xs font-semibold uppercase tracking-wider text-blue-600">Administration</div><h2 className="mt-1 text-2xl font-bold">Settings & governance</h2><p className="mt-1 text-sm text-slate-500">Brand your certificates, configure numbering, connect blockchain/IPFS metadata and manage the administrator account.</p></div><button onClick={save} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white"><Save size={17}/> {saved?"Saved":"Save settings"}</button></div>
   <div className="grid gap-5 lg:grid-cols-2">
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Building2 className="text-blue-600"/><div><h3 className="font-bold">Institution branding</h3><p className="text-sm text-slate-500">Used by certificate and email templates.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["institutionName","Institution name"],["officialEmail","Official email"],["website","Website"],["phone","Phone"],["address","Address"],["authorizedName","Authorized person's name"],["designation","Designation"]].map(([k,l])=><label key={k} className="block text-sm font-semibold sm:col-span-1">{l}<input value={settings[k]||""} onChange={e=>change(null,k,e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label>)}<label className="block text-sm font-semibold">Logo<input type="file" accept="image/*" onChange={e=>image("logoDataUrl",e.target.files?.[0])} className="mt-2 w-full text-xs"/></label><label className="block text-sm font-semibold">Signature<input type="file" accept="image/*" onChange={e=>image("signatureDataUrl",e.target.files?.[0])} className="mt-2 w-full text-xs"/></label></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Hash className="text-blue-600"/><div><h3 className="font-bold">Certificate numbering</h3><p className="text-sm text-slate-500">Configure readable, sequential certificate IDs.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Prefix<input value={settings.certificateNumbering.prefix} onChange={e=>change("certificateNumbering","prefix",e.target.value.toUpperCase())} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-semibold">Starting number<input type="number" value={settings.certificateNumbering.startingNumber} onChange={e=>change("certificateNumbering","startingNumber",Number(e.target.value))} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-semibold">Number length<input type="number" min="1" max="12" value={settings.certificateNumbering.numberLength} onChange={e=>change("certificateNumbering","numberLength",Number(e.target.value))} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="flex items-center gap-2 pt-7 text-sm font-semibold"><input type="checkbox" checked={settings.certificateNumbering.yearEnabled} onChange={e=>change("certificateNumbering","yearEnabled",e.target.checked)}/> Include year</label><div className="rounded-xl bg-slate-50 p-4 text-sm sm:col-span-2">Next example: <b>{settings.certificateNumbering.prefix}-{settings.certificateNumbering.yearEnabled?`${new Date().getFullYear()}-`:""}{String(settings.certificateNumbering.nextNumber).padStart(settings.certificateNumbering.numberLength,"0")}</b></div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Wallet className="text-blue-600"/><div><h3 className="font-bold">Blockchain</h3><p className="text-sm text-slate-500">MetaMask registration uses the deployed CertificateRegistry contract.</p></div></div><div className="mt-5 space-y-4"><label className="block text-sm font-semibold">Network<input value={settings.blockchain.network} onChange={e=>change("blockchain","network",e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="block text-sm font-semibold">Contract address<input value={settings.blockchain.contractAddress} onChange={e=>change("blockchain","contractAddress",e.target.value)} placeholder="0x..." className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="block text-sm font-semibold">RPC URL<input value={settings.blockchain.rpcUrl} onChange={e=>change("blockchain","rpcUrl",e.target.value)} placeholder="Optional public RPC" className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Database className="text-blue-600"/><div><h3 className="font-bold">IPFS / storage</h3><p className="text-sm text-slate-500">Store certificate files through your own upload gateway or service.</p></div></div><div className="mt-5 space-y-4"><label className="block text-sm font-semibold">IPFS gateway<input value={settings.ipfs.gateway} onChange={e=>change("ipfs","gateway",e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="block text-sm font-semibold">Upload endpoint<input value={settings.ipfs.uploadEndpoint} onChange={e=>change("ipfs","uploadEndpoint",e.target.value)} placeholder="https://your-api.example/ipfs/upload" className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><div className="rounded-xl bg-slate-50 p-3 text-xs text-slate-500">No secret token is stored here. Configure provider credentials on the backend/deployment environment.</div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><Mail className="text-blue-600"/><div><h3 className="font-bold">Gmail API connection</h3><p className="text-sm text-slate-500">Send certificates directly from praveen.kumaran0409@gmail.com using Google OAuth. No custom domain is required.</p></div></div>{gmail.loading?null:gmail.connected?<span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">Connected</span>:<button onClick={connectGmail} disabled={!gmail.configured} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Connect Gmail</button>}</div><div className={`mt-4 rounded-xl border px-4 py-3 text-sm ${gmail.connected?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>{gmail.loading?"Checking Gmail connection…":gmail.connected?`Authorized sender: ${gmail.from}`:gmail.message||"Configure Google OAuth credentials on Render."}</div>{!gmail.loading&&!gmail.connected&&gmail.configured&&gmail.authUrl?<p className="mt-3 text-xs text-slate-500">After authorization, copy the refresh token into Render as <code>GMAIL_REFRESH_TOKEN</code>, save it, and redeploy.</p>:null}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><div className="flex items-center gap-3"><Mail className="text-blue-600"/><div><h3 className="font-bold">Professional email template</h3><p className="text-sm text-slate-500">The delivery pages replace variables for each participant automatically.</p></div></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><label className="text-sm font-semibold">Subject<input value={settings.emailTemplate.subject} onChange={e=>change("emailTemplate","subject",e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-semibold lg:row-span-2">Body<textarea rows="8" value={settings.emailTemplate.body} onChange={e=>change("emailTemplate","body",e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2.5 font-normal"/></label><div className="rounded-xl bg-slate-50 p-4 text-xs text-slate-500">Available variables: <b>{'{{name}}'}</b>, <b>{'{{course}}'}</b>, <b>{'{{certificate_id}}'}</b>, <b>{'{{verification_url}}'}</b>, <b>{'{{institution_name}}'}</b></div></div></section>
   </div>
   <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><ShieldCheck className="text-blue-600"/><div><h3 className="font-bold">Administrator account</h3><p className="text-sm text-slate-500">Update the administrator profile and portal password.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold">Name<input value={profile.name||""} onChange={e=>setProfile({...profile,name:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-semibold">Email<input value={profile.email||""} onChange={e=>setProfile({...profile,email:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-semibold">New password<input type="password" placeholder="Leave blank to keep current" id="new-password" className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label></div><button onClick={()=>{const pw=document.getElementById("new-password").value.trim();saveUser({...profile,...(pw?{password:pw}: {})});localStorage.setItem("certichain-session-user",JSON.stringify({...profile,role:"Admin"}));setSaved(true);setTimeout(()=>setSaved(false),1600)}} className="mt-4 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Save admin account</button></section>
   <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-bold">Backup & restore</h3><p className="mt-1 text-sm text-slate-500">Export templates, certificates, settings and audit metadata. Secrets such as email-service secrets are never included.</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={backup} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white"><Download size={16}/> Download backup</button><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold"><Upload size={16}/> Restore backup<input hidden type="file" accept=".json,application/json" onChange={e=>restore(e.target.files?.[0])}/></label><button onClick={()=>{setSettings(loadInstitutionSettings());setSaved(false)}} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold"><RefreshCw size={16}/> Reload settings</button></div></section>
   <div className="rounded-2xl border border-amber-100 bg-amber-50 p-4 text-xs text-amber-900"><div className="flex items-center gap-2 font-semibold"><ShieldCheck size={16}/> Security reminder</div><p className="mt-1">Keep Gmail OAuth client secrets, refresh tokens, Pinata/API keys, private keys and RPC secrets in environment variables. Never include them in backups or commit them to Git.</p></div>
 </div></Layout>
}
